version: "3.8"

services:

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Berlin
      - MONGO_USER=unifi
      - MONGO_PASS=${MONGO_PASS:?err}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - ./network-application/config:/config
    networks:
      - web
      - backend
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  unifi-db:
    image: docker.io/mongo:latest
    container_name: unifi-db
    environment:
      - MONGO_USER=unifi
      - MONGO_PASS=${MONGO_PASS:?err}
      - MONGO_DBNAME=unifi
    networks:
      - backend
    volumes:
      - ./db/data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped

networks:

  web:
    internal: false

  backend:
    internal: true